### ISSUE TITLE
Profile URLs broken

### ISSUE THREAD

**Issue by mxbi** [camvote/bob-providers#2]
In the provider YAMLs, we have a `profileBaseUrl` set, which we currently set to the full URL of a provider's homepage (e.g. https://qjcr.org.uk)

This doesn't surface correctly on the website. Clicking on an organisation link e.g.
![image](https://user-images.githubusercontent.com/6796648/141682378-323866fd-81a1-430b-a1ee-1b968c766e36.png)

takes you to `http://camb.votehttps//qjcr.org.uk/`. The same bad link is visible in the ballot creation page among others

Two solutions:
1. Fix these links in the GUI
2. Change the YAMLs to set `profileBaseUrl=/qjcr` (for example)

**Comment by lewis-wf** [comment]
I favour changing YAMLs to that base URL format, which correctly displays in this format: `baseUrl: "/magdalenejcr/"`

- [x] Update baseUrls to id (such as "/magdalenejcr/")
- [x] Update all `profileBaseUrls` to `''`
